version: '2'
services:
  db:
    image: rethinkdb:latest
    ports:  
      - "38080:8080"
    labels:
      - "com.exampleup.proxy.name.38080:RethinkDB"
  web:
    image: markwatsonatx/node-alpine:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "33000:3000"
    depends_on:
      - db
    labels:
      - "com.exampleup.proxy.name.33000:Web"
